version: '3.4'

services:
     gerenciadortarefas.api:
       image: ${DOCKER_REGISTRY-}gerenciadortarefasapi
       build:
         context: .
         dockerfile: GerenciadorTarefas/Dockerfile
       ports:
         - "5000:80"
       depends_on:
         - sqlserver

     sqlserver:
        container_name: GerenciadorTarefasDb
        image: mcr.microsoft.com/mssql/server:2019-latest
        hostname: 'sqlserver'
        environment:
          SA_PASSWORD: ${DB_PASSWORD}
          ACCEPT_EULA: "Y"
        volumes:
          - c:\dados\volumes\mssql:/var/opt/mssql3
        ports:
          - "11433:1433"
        expose:
          - 1433